# Generated by Django 2.1.2 on 2019-03-26 07:04

from django.db import migrations
import kallisticore.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kallisticore', '0002_experiment_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='parameters',
            field=kallisticore.utils.fields.DictField(blank=True, default={}),
        ),
    ]
