# Generated by Django 2.1.2 on 2019-04-16 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kallisticore', '0003_trial_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='trial',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trials', to='kallisticore.Experiment'),
        ),
    ]
