# Generated by Django 2.1.2 on 2019-05-06 05:43

from django.db import migrations
import kallisticore.models.trial
import kallisticore.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kallisticore', '0004_auto_20190416_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='ticket',
            field=kallisticore.utils.fields.DictField(blank=True, default={},
                                              validators=[kallisticore.models.trial.validate_trial_ticket]),
        ),
    ]
