# Generated by Django 2.1.2 on 2019-05-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kallisticore', '0006_trial_initiated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
