# Generated by Django 2.1.2 on 2019-06-07 07:53

from django.db import migrations
import kallisticore.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kallisticore', '0007_trial_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='records',
            field=kallisticore.utils.fields.DictField(blank=True, default={}),
        ),
    ]
