# Generated by Django 2.1.2 on 2019-06-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kallisticore', '0010_auto_20190618_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialschedule',
            name='recurrence_left',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
