# Generated by Django 2.1.2 on 2019-07-09 10:27

from django.db import migrations, models
import kallisticore.models.trial
import kallisticore.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kallisticore', '0011_trialschedule_recurrence_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='pre_steps',
            field=kallisticore.utils.fields.StepsField(default=[]),
        ),
        migrations.AlterField(
            model_name='trial',
            name='status',
            field=models.CharField(default='Created', max_length=20, validators=[kallisticore.models.trial.validate_trial_status]),
        ),
    ]
