# Generated by Django 2.1.2 on 2019-08-16 09:32

from django.db import migrations, models
import kallisticore.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kallisticore', '0012_auto_20190709_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('emails', kallisticore.utils.fields.ListField(default=[])),
            ],
            options={
                'verbose_name': 'Notification',
            },
        ),
    ]
