# Generated by Django 2.1.2 on 2019-08-16 03:22

from django.db import migrations


def get_notification(apps):
    # We can't import the Notification model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    return apps.get_model('kallisticore', 'Notification')


def create_notification(apps, schema_editor):
    get_notification(apps).objects.create(emails=[])


def remove_notification(apps, schema_editor):
    get_notification(apps).objects.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('kallisticore', '0013_notification'),
    ]

    operations = [
        migrations.RunPython(code=create_notification, reverse_code=remove_notification),
    ]
