# Generated by Django 2.1.2 on 2019-09-06 07:02

from django.db import migrations, models
import kallisticore.models.trial


class Migration(migrations.Migration):

    dependencies = [
        ('kallisticore', '0014_notification_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='created_by',
            field=models.CharField(default='unknown', max_length=7),
        ),
    ]
