# Generated by Django 2.1.2 on 2019-09-10 02:40

from django.db import migrations, models
import kallisticore.models.trial


class Migration(migrations.Migration):

    dependencies = [
        ('kallisticore', '0015_auto_20190906_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('publish_trial', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Config',
            },
        ),
        migrations.AlterField(
            model_name='trial',
            name='status',
            field=models.CharField(default='Scheduled', max_length=20, validators=[kallisticore.models.trial.validate_trial_status]),
        ),
    ]
