# Generated by Django 2.1.2 on 2019-10-09 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kallisticore', '0017_config_seed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config',
        ),
    ]
