# Generated by Django 2.1.2 on 2020-12-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kallisticore', '0018_delete_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
